import numpy as np


w0 = 0.057
pi = np.pi
param = {"n_threads": 8,
         "init_wf": 1,
         "use_potential": 1,
         "geometry": 2,
         "ni": 200,
         "imin": 0.0,
         "imax": 100.0,
         "nj": 400,
         "jmin": -100.0,
         "jmax": 100.0,
         "nk": 400,
         "kmin": -100.0,
         "kmax": 100.0,
         "w0": w0,
         "period": 2*pi/w0,
         "tmax_ev": 4*2*pi/w0,
         "tmax_sim": 5*2*pi/w0,
         "dt": 0.08,
         "dt_ITP": 0.005,
         "nt": int(5*2*pi/w0/0.08),
         "nt_ITP": 100,
         "nt_diag": 100,
         "use_field_file": 1,
         "file_fieldx": "efields/fieldy.txt",
         "file_fieldy": "efields/fieldx.txt",
         "file_fieldz": "efields/fieldz.txt",
         "env": 0,
         "w0Ei": w0,
         "w0Ej": w0, 
         "w0Ek": w0,
         "w0Bi": w0,
         "w0Bj": w0,
         "w0Bk": w0,
         "E0i": 0.000,
         "E0j": 0.000,
         "E0k": 0.000,
         "B0i": 0.00,
         "B0j": 0.00,
         "B0k": 0.00,
         "phiEi": 0.0*pi,
         "phiEj": 0.0*pi,
         "phiEk": 0.0*pi,
         "phiBi": 0.0*pi,
         "phiBj": 0.0*pi,
         "phiBk": 0.0*pi,
         "n_probes": 3,
         "probe_def": ("acc_i,results/acc_i.dat;"
                       "acc_j,results/acc_j.dat;"
                       "acc_k,results/acc_k.dat;"
                       )
        }
